include:
  - https://cnb.cool/cnb/plugins/market/-/blob/main/hub.docker.com.yml

main:
  push:
    - services:
        - docker
      allow_failure: true
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        # 同名镜像构建&推送
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        # 自动打标签
        - name: auto tag
          image: cnbcool/git-auto-tag:latest
          settings:
            tagFormat: v\${version}
            branch: $CNB_BRANCH
            repoUrlHttps: $CNB_REPO_URL_HTTPS
          exports:
            tag: NEW_TAG
        # 同名镜像构建&推送
        - name: docker tag
          script: docker tag  ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest  ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${NEW_TAG}
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${NEW_TAG}
    - stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            embedding_model: hunyuan
            include: "**/*.md"
            exclude: "vendor/**"
            issue_sync_enabled: true
    # - services:
    #     - docker
    #   docker:
    #     volumes:
    #       - /data/codewiki/${CNB_REPO_SLUG}:data
    #   stages:
    #     - name: 生成 Code Wiki
    #       # 当仓库比较大时，codewiki 用时会超过流水线默认的1小时，导致流水线自动结束。所以手动指定流水线超时时间
    #       timeout: 2h
    #       image: cnbcool/codewiki:latest
    #       settings:
    #         git_doc_dir: /data/codewiki/${CNB_REPO_SLUG}     
  pull_request:
    - stages:
      - name: 代码评审
        image: cnbcool/ai-review:latest
        settings:
          type: code-review           
$:
  vscode:
    - docker:
        image: docker.cnb.cool/examples/language/golang-1.24
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls          
  tag_push:
    - stages:
        - name: changelog
          image: cnbcool/changelog
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: print changelog
          script: 
          - echo $LATEST_CHANGE_LOG
          - cat CHANGELOG.md
        - name: upload release
          type: git:release
          options:
            description: ${LATEST_CHANGE_LOG}
"**":
  web_trigger_code_import:
    - services:
        - docker
      stages:
        - name: 获取当前仓库根组织
          script: echo ${CNB_GROUP_SLUG} | awk -F '/' '{print $1}'
          exports:
            info: ROOT_GROUP_NAME
        # - name: 获取CNB URL
        #   script: echo ${CNB_WEB_ENDPOINT} 
        #   exports:
        #     info: CNB_URL    
        # - name: ECHO
        #   script: 
        #     - echo ${CNB_URL} 
        #     - echo ${ROOT_GROUP_NAME}                    
        - name: code-import
          script: |
            docker run --rm  \
            -e PLUGIN_SOURCE_URL=${PLUGIN_SOURCE_URL}  \
            -e PLUGIN_SOURCE_TOKEN=${PLUGIN_SOURCE_TOKEN}  \
            -e PLUGIN_SOURCE_PLATFORM=${PLUGIN_SOURCE_PLATFORM}  \
            -e PLUGIN_SROUCE_AK=${PLUGIN_SROUCE_AK}  \
            -e PLUGIN_SROUCE_SK=${PLUGIN_SROUCE_SK}  \
            -e PLUGIN_SOURCE_REGION=${PLUGIN_SOURCE_REGION}  \
            -e PLUGIN_CNB_URL=${CNB_WEB_ENDPOINT}  \
            -e PLUGIN_CNB_ROOT_ORGANIZATION=${ROOT_GROUP_NAME} \
            -e PLUGIN_CNB_TOKEN=${PLUGIN_CNB_TOKEN}  \
            -e PLUGIN_MIGRATE_ALLOW_INCOMPLETE_PUSH=${PLUGIN_MIGRATE_ALLOW_INCOMPLETE_PUSH} \
            -e PLUGIN_SOURCE_GROUP=${PLUGIN_SOURCE_GROUP} \
            -e PLUGIN_MIGRATE_MAP_CODING_DESCRIPTION=${PLUGIN_MIGRATE_MAP_CODING_DESCRIPTION} \
            -e PLUGIN_MIGRATE_MAP_CODING_DISPLAY_NAME=${PLUGIN_MIGRATE_MAP_CODING_DISPLAY_NAME} \
            -e PLUGIN_SOURCE_ORGANIZATIONID=${PLUGIN_SOURCE_ORGANIZATIONID} \
            -e PLUGIN_MIGRATE_REBASE=${PLUGIN_MIGRATE_REBASE} \
            -e PLUGIN_MIGRATE_FORCE_PUSH=${PLUGIN_MIGRATE_FORCE_PUSH} \
            -v $(pwd):$(pwd) -w $(pwd) \
            cnbcool/code-import
          timeout: 12h

  "web_trigger_同步Sealantern":
    - services:
        - docker
      stages:
        - name: code-import-sealantern
          script: |
            docker run --rm  \
            -e PLUGIN_SOURCE_URL=https://github.com  \
            -e PLUGIN_SOURCE_PLATFORM=github  \
            -e PLUGIN_SOURCE_REPO=SeaLantern-Studio/SeaLantern  \
            -e PLUGIN_MIGRATE_ORGANIZATION_MAPPING_LEVEL=2  \
            -e PLUGIN_MIGRATE_RELEASE=true  \
            -e PLUGIN_CNB_ROOT_ORGANIZATION=SeaLantern-studio \
            -e PLUGIN_SOURCE_TOKEN=${PLUGIN_SOURCE_TOKEN}  \
            -e PLUGIN_CNB_TOKEN=${PLUGIN_CNB_TOKEN}  \
            -e PLUGIN_CNB_URL=${CNB_WEB_ENDPOINT}  \
            -v $(pwd):$(pwd) -w $(pwd) \
            cnbcool/code-import
          timeout: 12h
       
