include:
  - https://cnb.cool/cnb/plugins/market/-/blob/main/hub.docker.com.yml

main:
  push:
    - services:
        - docker
      allow_failure: true
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        # 同名镜像构建&推送
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        # 自动打标签
        - name: auto tag
          image: cnbcool/git-auto-tag:latest
          settings:
            tagFormat: v\${version}
            branch: $CNB_BRANCH
            repoUrlHttps: $CNB_REPO_URL_HTTPS
          exports:
            tag: NEW_TAG
        # 同名镜像构建&推送
        - name: docker tag
          script: docker tag  ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest  ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${NEW_TAG}
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${NEW_TAG}
    - stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            embedding_model: hunyuan
            include: "**/*.md"
            exclude: ""
$:
  vscode:
    - docker:
        image: docker.cnb.cool/examples/language/golang-1.24
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls          
  tag_push:
    - stages:
        - name: changelog
          image: cnbcool/changelog
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: print changelog
          script: 
          - echo $LATEST_CHANGE_LOG
          - cat CHANGELOG.md
        - name: upload release
          type: git:release
          options:
            description: ${LATEST_CHANGE_LOG}
"**":
  web_trigger_code_import:
    - services:
        - docker
      runner:
        tags: cnb:arch:amd64
        cpus: 16
      stages:
        - name: code-import
          script: |
            docker run --rm  \
            -e PLUGIN_SOURCE_ORGANIZATIONID=${PLUGIN_SOURCE_ORGANIZATIONID}  \
            -e PLUGIN_SOURCE_URL=${PLUGIN_SOURCE_URL}  \
            -e PLUGIN_SOURCE_TOKEN=${PLUGIN_SOURCE_TOKEN}  \
            -e PLUGIN_SOURCE_PLATFORM=${PLUGIN_SOURCE_PLATFORM}  \
            -e PLUGIN_CNB_URL=${PLUGIN_CNB_URL}  \
            -e PLUGIN_CNB_ROOT_ORGANIZATION=${PLUGIN_CNB_ROOT_ORGANIZATION} \
            -e PLUGIN_CNB_TOKEN=${PLUGIN_CNB_TOKEN}  \
            -e PLUGIN_MIGRATE_ALLOW_INCOMPLETE_PUSH=${PLUGIN_MIGRATE_ALLOW_INCOMPLETE_PUSH} \
            -v $(pwd):$(pwd) -w $(pwd) \
            cnbcool/code-import
          timeout: 10h