include:
  - https://cnb.cool/cnb/plugins/market/-/blob/main/hub.docker.com.yml

main:
  pull_request:
    - stages:
        - name: 代码评审
          image: cnbcool/ai-review:latest
          settings:
            type: code-review
  push:
    - services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        # 同名镜像构建&推送
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        # 自动打标签
        - name: auto tag
          image: cnbcool/git-auto-tag:latest
          settings:
            tagFormat: v\${version}
            branch: $CNB_BRANCH
            repoUrlHttps: $CNB_REPO_URL_HTTPS
          exports:
            tag: NEW_TAG
        # 同名镜像构建&推送
        - name: docker tag
          script: docker tag  ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest  ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${NEW_TAG}
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${NEW_TAG}